server:
  servlet:
    context-path: /testA
  port: 8091
spring:
  application:
    name: s1
  datasource:
    primary:
      jdbc-url:  jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
      #配置成多数据源时不能使用默认的url，需要使用jdbc-url
      username: root
      #password: 1234
      password: 1111a!
      driver-class-name: com.mysql.jdbc.Driver
    second:
      jdbc-url:  jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
      username: root
      #password: 1234
      password: 1111a!
      driver-class-name: com.mysql.jdbc.Driver
    third: #mycat连接方式及配置
      jdbc-url:  jdbc:mysql://localhost:8066/TESTDB?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
      username: root
      #password: 1234
      password: mycatUser
      driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    database: mysql
#    show-sql: true
#    hibernate:
#      ddl-auto: none
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8090/regist/eureka/